apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: bob:1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bob
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bob
    spec:
      containers:
      - image: nginx
        name: bob
        resources: {}
status: {}


