apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bob
  name: bob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bob
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bob
    spec:
      containers:
      - image: nginx
        name: bob
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: service-bob
  namespace: defaut
spec:
  ports:
    - port: 80
  type: ClusterIP
  selector:
    app: bob
